server:
  port: 8098

MLC:
#  每个搜索引擎查询的结果数量，如果可用的话
  pageNum: 50
  music163:
    MUSIC_U:

spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名